collin80/SavvyCAN

canframemodel.cpp
canframemodel.h
flowviewwindow.cpp

Merge in the stability fixes from WIP to WIP2

Merge WIP into WIP2

---

dbchandler.cpp
dbcloadsavewindow.cpp
dbcmaineditor.cpp
dbcsignaleditor.cpp
framefileio.cpp
framefileio.h
serialworker.cpp

Thank you Collin for savvycan. It looks really promising.
I run into a couple of UI bugs that you might want to look at.
Best,
canpadawan

a few bug fixes and initial support for candump/kayak log file format

---

SavvyCAN.pro
canframemodel.cpp
canframemodel.h
connections/canconmanager.cpp
dbcmaineditor.cpp
dbcmaineditor.h
mainwindow.cpp
mainwindow.h
mainwindow.ui
re/sniffer/snifferitem.cpp
re/sniffer/snifferitem.h
re/sniffer/sniffermodel.cpp
re/sniffer/sniffermodel.h
re/sniffer/snifferwindow.cpp
re/sniffer/snifferwindow.h
snifferwindow.ui
utility.h

Hi Collin,
I have added a sniffer and fixed a couple of bugs in the dbc editor
Best,
Vincent

cansniffer

---

README.md

Some of the markdown was not correct GFM and thus not rendering.  This should make the README easier to read on GitHub.

Improve formatting of the README

---

connections/socketcan.cpp

Hi Collin,
I've just discovered your SavvyCAN, a very nice project.
It makes especially happy that you are using QtSerialBus, and I like to provide some improvements in this area. This pull request is a start, and let's see, maybe more will come.
Feel free to comment on any change before accepting it, I can stand it ;)

Socketcan improvements

---

re/isotp_interpreterwindow.cpp
re/isotp_interpreterwindow.h
ui/isotp_interpreterwindow.ui

Add extended addressing to iso tp window

---

README.md
SavvyCAN.pro
connections/canconfactory.cpp
connections/canconnectionmodel.h
connections/serialbusconnection.cpp
connections/serialbusconnection.h
mainwindow.cpp
mainwindow.h

Hi Collin,
this is another merge request cleaning up some things while working on a better QtSerialBus integration (i.e. supporting the other CAN adapters from QCanBus: Peak, Systec, Vector and Tiny). While this work will need some more testing from my side, I think these patches here can already go in - if you agree.
Regards,
Andre

Serialbus and general cleanup

---

connections/serialbusconnection.cpp

Correctly receive error frames and use the socketcan "standard" for flagging them as error frames.
For now only works for socketcan interfaces.
It would be nice to be able to decode them but at least now they are not shown with an incorrect ID.

Fix reception of error frames in socketcan interface.

---

connections/serialbusconnection.cpp

This line was accidentally removed in the previous pull request.

Add accidentally removed line.

---

blfhandler.cpp
bus_protocols/isotp_handler.cpp
can_structs.h
canframemodel.cpp
connections/gvretserial.cpp
connections/serialbusconnection.cpp
framefileio.cpp
framesenderwindow.cpp
mainwindow.cpp
re/fuzzingwindow.cpp
scriptcontainer.cpp

Remote frames were received incorrectly, this makes SavvyCAN aware of them and fixes some log file loaders for which I knew the file format, the rest were left with the old behaviour, no remote frames.

Make SavvyCAN aware of remote frames.

---

connections/serialbusconnection.cpp

It caused data bytes not to show up

Fix for bug recently introduced into SocketCAN handler

---

framefileio.cpp
framefileio.h

Haven't tested this as I don't have a Linux machine handy to build it on, but the majority of the code is copy/pasted from other file loaders/savers. Should allow for importing of log files from Cabana.

Add load/save for Cabana log files.

---

can_structs.h
canframemodel.cpp
config.h
connections/canconmanager.cpp
dbc/dbchandler.cpp
dbc/dbchandler.h
dbc/dbcloadsavewindow.cpp
dbc/dbcmaineditor.cpp
framefileio.cpp
framefileio.h
mainwindow.cpp
qcustomplot.cpp
qcustomplot.h
re/graphingwindow.cpp
re/graphingwindow.h
re/newgraphdialog.cpp
re/newgraphdialog.h
ui/newgraphdialog.ui

Merge WIP into Master

---

main.cpp
mainsettingsdialog.cpp
mainsettingsdialog.h
mainwindow.cpp

https://github.com/collin80/SavvyCAN/issues/196

#196: fix persistent settings on Ubuntu 19.04

---

framefileio.cpp

* Properly decode and encode extended IDs
* Properly decode and encode RTR messages

Fix Decoding of Canalzyer ASC files

---

canframemodel.cpp
framefileio.cpp
framefileio.h

Related https://github.com/collin80/SavvyCAN/pull/243

Save CARBUS Analyzer format

---

framefileio.cpp
framefileio.h

Support for reading log files generated by CLX000 devices from CSS Electronics.

Add support for detecting and reading CLX000 files.

---

.github/workflow/build.yml

This is an initial PR for building the three OS's builds using Github Actions.
Presently there isn't any signing done on the macos build.

Build mac/windows/linux packages using github actions

---

scriptcontainer.cpp

The ISOTP and UDS data bytes were not initialized correctly as 'msg.payload().length()' !
Essentially fix these 2 bugs here:
https://github.com/collin80/SavvyCAN/blob/fb2e7c473ea36e432cd4e213157e046b46ddcac9/scriptcontainer.cpp#L314
https://github.com/collin80/SavvyCAN/blob/fb2e7c473ea36e432cd4e213157e046b46ddcac9/scriptcontainer.cpp#L394

Fix bugs in script send ISOTP+UDS data bytes

---

jsedit.cpp
jsedit.h
scriptingwindow.cpp

* Show whitespaces in Scripting Window
* Highlight custom objects, callback functions and functions with a custom flashy color

Scripting rework

---

re/flowviewwindow.cpp
re/flowviewwindow.h
re/frameinfowindow.cpp
re/frameinfowindow.h
re/sniffer/sniffermodel.cpp
re/sniffer/snifferwindow.cpp
re/sniffer/snifferwindow.h
ui/flowviewwindow.ui
ui/frameinfowindow.ui

Hi
I've added some new features to some of the RE tools:
- Frequency display under the Sniffer tool
- Flow View : 
- Graph Range slider
- Enable/Disable charts
- Timeline slider
- Enable/Disable charts under Frame Info tool

Misc UI additions

---

re/graphingwindow.cpp

Fixes #320.
Note: Interpolation is still not quite correct and may have remaining artifacts at the epsilon-T region.

GraphingWindow: improve interpolation for CSV-export.

---

connections/canconfactory.cpp

restore network connection was not working because it was detected as serial by this modification it is working

Solve restore network connection  not working

---

qcustomplot.h

Cf the discussion here: https://www.qcustomplot.com/index.php/support/forum/2380

make QCustomPlot compatible with Qt6.2+ (qt6)

---

.gitignore
SavvyCAN.pro
connections/canconconst.h
connections/canconfactory.cpp
connections/canconmanager.cpp
connections/canconnectionmodel.cpp
connections/canserver.cpp
connections/canserver.h
connections/newconnectiondialog.cpp
connections/newconnectiondialog.h
ui/newconnectiondialog.ui

This PR adds support for streaming data over the network from a CANserver.

Canserver live support

---

re/udsscanwindow.cpp
re/udsscanwindow.h

Before it always used the first bus no matter what.

Use selected can bus in uds scanner.

---

.github/workflows/build.yml
connections/lawicel_serial.cpp

I am not a C++ developer but I have tried to implement the processing of extended CAN BUS frames for SLCAN/LAWICEL. The frames are displayed correctly in the debug.

Add Extended CAN Bus Frame to SLCAN/LAWICEL

---

framefileio.cpp

CANserver firmware 2.2.0 will be adding a new logging format that support us resolution for timestamps of received frames.

Support higher time resolution CANserver format

---

connections/lawicel_serial.cpp
connections/lawicel_serial.h

Fixed System Clock timestamps and added decoding for timestamps coming from the tool.

Added/corrected timestamps for LAWICEL protocol.

---

SavvyCAN.pro

https://github.com/collin80/SavvyCAN/issues/853

Fix icons output dir

---

connections/canconfactory.cpp
connections/canconnection.cpp
connections/canconnection.h
connections/connectionwindow.cpp
connections/serialbusconnection.cpp
connections/serialbusconnection.h

This modification saves the canbus speed , serial speed and databus rate as well as the can-fd state for all saved connections.

Implemented connection save with speeds and can fd at least for bus 0.

---

install-linux.sh

For me the existing script (install.sh) didn't work, so I made this. I believe this should work on majority of linux distros. Tested on Debian (Bookworm).

chore: add installer script for linux

---

re/fuzzingwindow.cpp
re/fuzzingwindow.h
ui/fuzzingwindow.ui

Add these buttons to improve productivity.
I don't know what's wrong with the font, but it is working.

FuzzingWindow: Add buttons to set all high/low/auto

---

.github/workflows/build.yml
dbc/dbchandler.cpp

Minor updates for Github CI.
Updated Windows 2019 to 2022 (the first one is not supported now) and Visual Studio (standard windows image doesn't include MSVC 2019).
Also minor fixes to remove warnings. But please note that I haven't tested Notify Discord task, since I'm too lazy to setup environment ;)
Also there is duplicate of #952, since I cannot build app without it.

Update Github actions
