collin80/SavvyCAN

- can_structs.h
- canbus.cpp
- canbus.h
- canframemodel.cpp
- connections/canconconst.h
- connections/canconnection.cpp
- connections/canconnection.h
- connections/gvretserial.cpp
- connections/gvretserial.h
- connections/socketcan.cpp
- connections/socketcan.h
- connectionwindow.cpp
- connectionwindow.h
- filecomparatorwindow.cpp
- framefileio.cpp
- mainwindow.cpp
- scriptcontainer.cpp
- test/main.cpp
- test/test.pro
- test/tst_cancon.cpp
- test/tst_cancon.h
- test/tst_lfqueue.cpp
- test/tst_lfqueue.h
Hi Collin,
I have done a couple of tests to get the best possible reactivity when a can frame of interest arrives.
2 approaches:
* allow for a c++ callback in the CANConnection (supposed to be faster than qt signals)
* in the callback I'm queuing a method call to wake up the UI thread
* only if there is not one already ongoing
* I must say I was confident but there are still far too many events for this method to be useful. The UI is always smooth but the UI threads always consumes 100% of one core since I am more or less enqueuing one new wake up call once the previous has returned.
* on laptop, this would waste battery for nothing
* use filters:
* I have added support for filters in the CanConnection.
* this is almost transparent for connection implementer (2 extra lines) 
* …
> test for better reactivity

- SavvyCAN.pro
- canbus.cpp
- canbus.h
- canconnectionmodel.cpp
- canconnectionmodel.h
- canfilter.h
- canframemodel.cpp
- canframemodel.h
- connections/canconmanager.cpp
- connections/canconmanager.h
- connections/canconnection.cpp
- connections/canconnection.h
- connections/socketcan.cpp
- connectionwindow.cpp
- connectionwindow.h
- connectionwindow.ui
- mainwindow.cpp
- mainwindow.ui
- scriptcontainer.cpp
- scriptcontainer.h
- scriptingwindow.cpp
- scriptingwindow.h
I have added a CANConManager which receives all the frames from the different CANConnections and dispatch them on the UI thread through a signal.
I have added this reception mode to CANFrameModel and tried to add it to scriptingwindow as well but I must say it's not perfect for the latter.
the scriptingwindow should probably have a combobox to select on what canconnection and what bus the script is active.
I have also worked on the canconnectionwindow. I think It's still not really intuitive but at least it now works... 
Also the connection configuration is now persistent through app restart.
It's worth noting that many windows require rework & code cleaning to correctly use the new canconnection abstraction.
You tell me what you think.
Best,
Vincent
> CANConManager and example of usage for javascript

- SavvyCAN.pro
- connections/connectionwindow.cpp
I modified two things.  The first is fixing the compile error.
../SavvyCAN/connections/connectionwindow.cpp: In member function ‘bool ConnectionWindow::isSocketCanAvailable()’:
../../Qt5.8.0/5.8/gcc_64/include/QtCore/qglobal.h:944:34: error: invalid initialization of reference of type ‘const QByteArray&’ from expression of type ‘const QString’
for (variable = *_container_.i; _container_.control; _container_.control = 0)
...by changing using auto (already using C++11 so why not?)
The second is that you don't need to download and install QScintella on Ubuntu.  You can just 
$ sudo apt-get install libqt5scintilla2-11 libqt5scintilla2-dev
...and it should work with the .pro file changes.
> Fix Compile/build on Ubuntu 14.04

- ui/connectionwindow.ui
Is was not visible when connection window was at minimum size.
> Fix port widget height in connection window.

- .gitignore
- dbc/dbc_classes.cpp
- dbc/dbchandler.cpp
- dbc/dbchandler.h
- dbc/dbcloadsavewindow.cpp
Ignore the source address part of the ID when a database is marked as a J1939 database.
I could not find a way to center the checkbox on the DBC file dialog without subclassing or complicating the signal handling for the checkbox, so I leave it that way.
> Manage J1939 databases

- mainwindow.cpp
- mainwindow.h
- re/isotp_interpreterwindow.cpp
- re/isotp_interpreterwindow.h
That seems very native action to me, just feeling upset when frames are not sorted after a table header was clicked. I don't have any experience with Qt but it seems that QSortFilterProxyModel implements sort for most basic data types, so sorting seems to work somehow.
> Add sorting after table header click for main and isotp windows

- dbc/dbchandler.cpp
This was causing the DBC handler to threat a DBC file as a J1939 database during the parsing, even though the files where not marked as a j1939 database. Maybe it would be better to move the attributes definition to the start of the DBC file.
> Fix DBC handler and DBCFile. Initialize as j1939 to false by default.

- mainwindow.cpp
Allow to freely scroll the captured frames window in suspended state.
Fixes #111
> FramesView: Fix auto scrolling when frame capturing is suspended

- framefileio.cpp
Set the extended flag if the number of characters of the ID is more than 3
> Fix loading of candump log files with extended frames.

- framefileio.cpp
- framefileio.h
This PR adds read support for the trace files generated by CANHacker. The software is obsolete and has been for a while, yet I still like to use it and reading the files is pretty straightforward.
> Add Read Support for CANHacker trace files (.trc)

- connections/connectionwindow.cpp
- mainwindow.cpp
Commit 03f8e2c makes SavvyCAN save settings on startup but types used for connection settings were not registered so the connection configuration was lost.
> Register metatypes before loading and saving configuration.

- connections/canconfactory.cpp
- connections/gvretserial.cpp
- connections/gvretserial.h
Added bool passed to GVRETSerial to indicate when to use TCP,
rather than infering from port name.
I'm not sure this is the best way to do it, but I'm pretty confident you want to tell GVRETSerial explicitly to use TCP. On my Mac serial ports all look like "cu.usbmodemxxxx", so SavvyCAN won't connect to them.
> Fix Serial Ports with dots

- bisectwindow.cpp
- connections/connectionwindow.cpp
- dbc/dbcloadsavewindow.cpp
- firmwareuploaderwindow.cpp
- frameplaybackwindow.cpp
- framesenderwindow.cpp
- helpwindow.cpp
- motorcontrollerconfigwindow.cpp
- re/discretestatewindow.cpp
- re/filecomparatorwindow.cpp
- re/flowviewwindow.cpp
- re/frameinfowindow.cpp
- re/fuzzingwindow.cpp
- re/graphingwindow.cpp
- re/isotp_interpreterwindow.cpp
- re/rangestatewindow.cpp
- re/sniffer/snifferwindow.cpp
- re/udsscanwindow.cpp
- scriptingwindow.cpp
- signalviewerwindow.cpp
* improves window handling a lot
(on Linux GNOME 3 at least: quickly resizing windows left/right, not forced in foreground anymore etc.)
setWindowFlags() inserted in all *window.cpp files except mainwindow
* some whitespace at EOL trimmed
> add setWindowFlags(Qt::Window) to improve window management

- framefileio.cpp
It generated a segfault when loading a busmaster log file with auto detection.
> Fix candump file detection.

- connections/newconnectiondialog.cpp
Something like this may be useful for people wondering why SocketCAN isn't working.
> show tooltip for socketCAN error string

- re/frameinfowindow.cpp
- ui/frameinfowindow.ui
This pull request adds additional timing info to the Frame Data Analysis window:
* Standard deviation of the inter-frame intervals
* Minimum range to fit 90% of inter-frame intervals. This is similar to the inter-frame interval variation but less prone to single outliers
* A histogram showing the distribution of interval-lengths
This information can be used to identify, whether messages are sent on a cyclic interval (low variance in interval-length) or event-based (high variance in interval-length).
Additionally, the calculation of the existing interval information has been changed to use uint64_t instead of int to avoid integer overflows when processing large datasets (for average interval) or IDs with long delays in-between (for min/max interval).
> Add additional timing information and a histogram of intervals

- frameplaybackwindow.cpp
Hi!
Problem of Exception in Playback window.
If you check / uncheck an item that exists in ID Filtering with all sources in the Playback Sequence deleted, Null pointer access occurs and the program crashes at Segmentation fault.
This is because "currentSeqItem" is null in changeIDFiltering.
Changing the code in two places will fix this problem.
> Fix null pointer access in Playback window

- docs/source/mainscreen.rst
- framefileio.cpp
This pull request adds support for reading/writing the latest CRTD format (with bus number). The specification for CRTD is now here:
https://docs.openvehicles.com/en/latest/crtd/
As well as the R11/R29/T11/T29 types, we now support an optional bus number prefix (e.g. 1R11, 2T29, etc). If not specified, then bus #1 is to be assumed.
> Add support for reading/writing the latest CRTD format (with bus number)

- SavvyCAN.pro
- canframemodel.cpp
- canframemodel.h
- dbc/dbchandler.cpp
- dbc/dbchandler.h
- dbc/dbcloadsavewindow.cpp
- dbc/dbcloadsavewindow.h
- filterutility.cpp
- filterutility.h
- frameplaybackwindow.cpp
- mainsettingsdialog.cpp
- mainwindow.cpp
- re/flowviewwindow.cpp
- re/frameinfowindow.cpp
- re/fuzzingwindow.cpp
- ui/dbcloadsavewindow.ui
- ui/mainsettingsdialog.ui
- Save DBC file configuration when changed, and restore it when restarting the application (no need for manual entry everytime app is launched)
- Add GMLAN 29bit filtering feature. In addition to J1939 matching, it is now possible to match DBC messages using only the Arbitration Id (bits 14-26 of CAN Address), since  Priority id (higher bits) and Sender Id (lowest 13 bits) are not relevant when interpreting the CAN message content. This allows to use the excellent GM Global A DBC files on https://github.com/commaai/opendbc. Just remember to select the "GMLAN" matching criteria on DBC File manager.
- Add "Filter labeling" feature. Using loaded DBC files, it matches the filter Ids with DBC messages and shows them in filter windows. Labeling works in the main window (no need to set "Frame …
> DBC configuration saving, GMLAN 29bit Arbitration ID Matching, Filter labeling

- dbc/dbcloadsavewindow.cpp
- dbc/dbcloadsavewindow.h
- mainwindow.cpp
- mainwindow.h
- Changes in DBC file manager (such as changing the bus, matching criteria, filter labeling) are immediately propagated to the main window (frame interpreting, filter labeling)
- Prevent DBC file manager from saving settings too often and too early (this also fixes a bug where sometimes the settings of all but the first DBC file are lost)
> DBC settings and bugfixes

- re/graphingwindow.cpp
RTR messages will be incorrectly graphed as "0", even though it's not a real message.
> [graphing] Ignore RTR messages

- dbc/dbc_classes.cpp
- dbc/dbchandler.cpp
- dbc/dbcsignaleditor.cpp
I have an application where data is packed into canframes as little endian floats.
This PR has minor modifications to allow for floating point endianness:
- Removes the explicit deselection of endian checkbox when float types are set.
- Passes the endianess into the processIntegerSignal function when decoding floats.
In order to allow for loading and saving from DBC files, I have added new cases (5- and 6-) for `sig.valType`. This isn't the most elegant solution, but it maintains backward compatibility. 
Another option is to add support for the SIG_VALTYPE_ token. I am very familiar with what specifications are around for DBC but I have seen this implementation:
`SIG_VALTYPE_ <frame_id> <signal_name> : <type ex. 1 for float, 2 for double>;`
This may be a better option for supporting …
> Add support for Little Endian Floats

- dbc/dbc_classes.cpp
- dbc/dbc_classes.h
Numbers are formatted as floating point numbers, which looks
a bit crap for things like e.g. serial numbers (we don't need
mantissa and exponent). This change checks the scaling factor,
and if it is integer representable, the resulting number is
formatted as an integer number as that's most likely what's
intended, particularly if the factor is 1.
> Use integer formatting where possible when interpreting signal.

- framesenderwindow.cpp
Documentation says that trigger should be 'id' followed by the ID and gives the example 'id0x200'. This PR changes parsing to match the docs, previously the character between prefix and number was ignored, so that 'id:0x200' would work, but 'id0x200' would not.
> Modify the parsing of the 'id' trigger to match help

- main.cpp
Allow for local/per-application support for extensions to the base Qt modules. This allows the end users to place extensions under a local folder named `plugins`.
This could be new QCANBus classes (placed in `plugins/canbus/`), enabling streaming from additional logger hardware.
> Enable support for local plugins

- framefileio.cpp
Uses numBytes instead of thisFrame.payload().length() as the payload is not yet defined
Scan the first 25 lines instead of 10 as version 1 has a long header
For reference the file format is defined here : https://www.peak-system.com/produktcd/Pdf/English/PEAK_CAN_TRC_File_Format.pdf
> Fix PCAN loading issues

- connections/serialbusconnection.cpp
Enable support for marking messages recevied via QCanBus as Tx, if the device has marked them as such by utilizing `hasLocalEcho`.
Unsure if messages sent via SavvyCAN will occur in the list twice if connected to a bus with Tx capabilities (The tested device has a config with periodic messages, but does not accept Tx over the remote interface).
> Support for Tx when logging via QCanBus

- framefileio.cpp
Seems I was a bit too stringent with the parser rules at first.
> CLX000: Allow for shorter IDs, flip direction

- SavvyCAN.pro
this has been bugging me when merging my branches, since I compile in Qt using mingw...
now it should work with both compilers under windows
> fixing opengl32 lib for g++ and msvc in windows

- re/graphingwindow.cpp
- re/graphingwindow.h
I'm a new user on OS X, and have had a bit of trouble zooming on the graph window when dealing with logfile data. (I use the recent CLX support!)
This implements: https://github.com/collin80/SavvyCAN/issues/300 as:
- Double-clicking an axis now resizes that axis to the available data.
- When at least one graph is plotted, offers an action in the context menu to rescale the view to the data.
I would be glad to update the helpfile appropriately; just indicate how you'd like it done.
> GraphWindow: support rescaling the view or each axis to the data

- blfhandler.cpp
When processing a BLF_CAN_MSG2 object the frame data was not actually
included in the imported frame.
> Fix blf import for BLF_CAN_MSG2

- ui/mainwindow.ui
Simple patch to make Ctrl-O (or Cmd-O on the mac) work for opening files
> Add a keyboard shortcut to the open menu

- bus_protocols/isotp_handler.cpp
The ISOTP Consecutive Frames start from 0x21 (2: Frame type, 1: Sequence number) and not 0x20 !
> Fix bug ISOTP CF 0x20

- framefileio.cpp
Frames were always showing up as 8 bytes and were padded with 0's from the left incorrectly.
This properly unpacks frames shorter then 8 bytes and shifts their bytes so they are in the correct spot and not left padded
> Correctly unpack bytes from a cabana file

- SavvyCAN.pro
- framefileio.cpp
- framefileio.h
- pcaplite.cpp
- pcaplite.h
Support for reading pcap and pcapng Wireshark CAN capture files.
Very lightweight file parser implemented, API compatible(only for the functionalities used to load pcap and pcapng CAN logs) with the official pcap implementation eliminating the external dependency to pcap.
>  Support for reading Wireshark files

- canframemodel.cpp
Currently, sorting loops all data bytes in a CAN frame into a 64 bit comparison value. In case of CAN FD frames, this will result in a negative bitshift, resulting in undefined behavior.
This selects up to the first 8 bytes, such that the bitshift never is a negative value.
> Avoid undefined behavior if FD frame datalengths are present in sorting

- README.md
When building from source `qmake` failed, so I installed the stated dependencies. However it still failed.
Some little search gave the missing package: `libqt5serialport5-dev``
In this PR I added it to the list.
> readme: fix QT module dependencies

- .gitignore
- `.qmkae.stash` and `Makefile` are generated by `qmake` command
- `SaavyCan` is default executable name for linux builds
- ignore a local VS code config file
> ignore more build files

- framesenderwindow.cpp
…and then added as a data byte
This affected editing of the data in the table as well as loading data from a saved file
> Fixed data string parsing bug where a trailing space is treated as a zero

- canframemodel.cpp
- connections/socketcand.cpp
The startup failure to switch to raw mode was due to data frames coming in the same message as the "< ok >" ack message for the switch to raw, so added parsing to check for these cases
The partial frame failure was an index out of bounds crash that came from assuming only complete frames would be received and the parser would always return a certian number of substrings, so added some sanity checking
> Fix two socketcand issues: start up switch to raw mode, crash due to partial frame

- dbc/dbchandler.cpp
- dbc/dbchandler.h
- dbc/dbcmaineditor.cpp
These issues were very repeatable, the delete node issue would fail trying to remove any node that contained a comment and the delete message issue came from deleting messages that weren't last in the list and the code continuing to go through the list comparing message name to the deleted message name which was no longer allocated/valid.
> Fix dbc delete node non-function and dbc delete message occasional crash

- canframemodel.cpp
- mainsettingsdialog.cpp
- ui/mainsettingsdialog.ui
Made max # of frames an option in preferences, restart to take effect
Prevent bad_alloc crash by limiting size and capacity of frames and filteredFrames to the user selected size.  Can still crash if this number is set too large, but at least user has control now.
When 99% capacity is reached then remove the first 5% of items in the two vectors.  
This causes the mainWindow table view to automatically renumber the rows.
Size is checked and adjusted in addFrames is called.
> Fix frames and filteredFrames from growing until out of memory

- mainwindow.cpp
- mainwindow.h
- re/sniffer/snifferitem.h
Since Qt5, some methods of QTime [are deprecated](https://doc.qt.io/qt-5/qtime-obsolete.html).
Qt6 remove those methods, thus in two instances we need to use a [QElapsedTimer](https://doc.qt.io/qt-6/qelapsedtimer.html) instead of a QTime.
QElapsedTimer is available since Qt5.4, and is already used in the source code.
> replace QTime with QElapsedTimer when possible (qt6)

- scriptingwindow.cpp
- simplecrypt.cpp
Since Qt5, qrand/qsrand methods [are deprecated](https://doc.qt.io/qt-5/qtglobal-obsolete.html#qrand).
Qt6 remove those methods, thus we need to use instead a [QRandomGenerator](https://doc.qt.io/qt-6/qrandomgenerator.html).
QElapsedTimer is available since Qt5.10, and is already used in the source code.
> replace qrand/qsrand with QRandomGenerator (qt6)

- connections/connectionwindow.cpp
- mainwindow.cpp
Since Qt6, some methods of [QMetaType are removed](https://doc.qt.io/qt-6/qtcore-changes-qt6.html#the-qmetatype-class).
We remove `qRegisterMetaTypeStreamOperators()` calls for Qt >= 6
> remove qRegisterMetaTypeStreamOperators (qt6)

- canframemodel.cpp
Since long time ago (12yrs), Qt::BackgroundColorRole/Qt::TextColorRole are aliased by Qt::BackgroundRole/Qt::ForegroundRole and raise a deprecation warning.
Qt6 remove those values, thus we need to use Qt::BackgroundRole/Qt::ForegroundRole.
> replace BackgroundColorRole/TextColorRole with BackgroundRole/ForegroundRole (qt6)

- connections/canconnection.cpp
Since Qt5, some methods of QAtomicInteger [are deprecated](https://doc.qt.io/qt-5/qatomicinteger-obsolete.html).
Qt6 remove those methods, thus we need to replace them.
> replace QAtomicInt load()/store() with loadRelaxed()/storeRelaxed()

- framesenderwindow.cpp
`QString::SkipEmptyParts` is [deprecated since around Qt5.14](https://doc.qt.io/qt-5/qstring-obsolete.html), and has been removed in Qt6.
We replace it with `Qt::SkipEmptyParts` for Qt >= 5.14
> replace `QString::SkipEmptyParts` with `Qt::SkipEmptyParts` (qt6)

- connections/gvretserial.cpp
Three enums (`QSerialPort::ParityError`, `QSerialPort::FramingError`, `QSerialPort::BreakConditionError`) are [deprecated since Qt5.6](https://doc.qt.io/qt-5/qserialport.html) and removed from Qt6.
We remove them, it's unfortunate but I don't know how to replace these - it seems that we need to handle those in an [OS-specific way](https://codereview.qt-project.org/c/qt/qtserialport/+/125517/).
> remove `QSerialPort` obsolete enum values (qt6)

- re/sniffer/sniffermodel.cpp
It seems that on my compiler we need to use an explicit enum instead of the constant it represents.
It shouldn't cause any issue as the value is the same.
> Use enums from `Qt::ItemFlags`

- mqtt/qmqtt_client.h
Prevent error:
```
moc_qmqtt_client.cpp:459:53: error: conversion from 'QMQTT::ConnectionState' to 'QChar' is ambiguous
```
> fix QMqtt ambiguous conversion

- mqtt/qmqtt_socket.cpp
- mqtt/qmqtt_ssl_socket.cpp
The following error occurs twice:
```
mqtt/qmqtt_ssl_socket.cpp:49:13: error: static_cast from 'QAbstractSocket::SocketError (QAbstractSocket::*)() const' to 'void (QSslSocket::*)(QAbstractSocket::SocketError)' is not allowed
```
It may not be the cleanest fix but the it is the only one I could come with...
> fix some static cast errors in QMqtt

- jsedit.cpp
The function `QWheelEvent::delta()` is [deprecated in Qt5](https://doc.qt.io/qt-5/qwheelevent-obsolete.html#delta), and has been removed in Qt6.
We port it to `QWheelEvent::angleDelta()`.
> remove obsolete `QWheelEvent::delta()` (qt6)

- dbc/dbchandler.cpp
Hi Collin,
I had a case where two ECUs were sending the same PGN (with different contents though), leading to SavvyCAN picking the first found PGN-Match.
Hence my proposal: go over the list until an exact match is found, otherwise returning the best match (same PGN for J1939).
> Priorizing exact match over J1939 and GMLAN

- connections/socketcand.cpp
Messages with 0 data bytes were being tossed by socketcand parser
> Fix socketcand empty frame drop

- connections/socketcand.cpp
- mainwindow.cpp
- mainwindow.h
- re/graphingwindow.cpp
- ui/mainwindow.ui
More standard way of looking at parsed data
Handles multiple message types. Each message gets its own columns.
With many message types there are a lot of blank cells but its easy to
analyze.
> Add mainmenu option to export decoded data as csv

- connections/canbus.cpp
- connections/canbus.h
- connections/connectionwindow.cpp
- connections/serialbusconnection.cpp
- ui/connectionwindow.ui
Added support for CAN FD frames to the SERIALBUS.
Now CAN FD frames will be displayed.
Example to check:
`❯ cansend vcan0 123##3112233445566778899aabbccddeeff`
> Added support for CAN FD frames to the SERIALBUS

- canframemodel.cpp
- canframemodel.h
- connections/canconmanager.cpp
- connections/canconnection.cpp
- connections/connectionwindow.cpp
- connections/socketcand.cpp
- connections/socketcand.h
- framesenderwindow.cpp
- framesenderwindow.h
- main.cpp
- mainwindow.cpp
- mainwindow.h
- re/flowviewwindow.cpp
- re/flowviewwindow.h
- re/graphingwindow.cpp
- re/graphingwindow.h
Main issue was due to queueing the TX frame from the wrong thread.
I originally thought it was due to how frames vs filteredframes was managed, so cleaned that up and while I was at it I changed frames to always contain all history and filteredframes to reflect the filters in the main window.  This obviously didn't fix the issue but it did make it so graphingwindow gets continuous data even when filters are active, and other such things like that.  I liked it so much I decided to keep it.
A couple other minor bug fixes related to doModifiers parsing crash in custom frame sender, fixed count cell not counting if not manually initialized, and a couple other things.
> Fix custom frame sender crashing

- .github/workflows/build.yml
Changed the name of the ZIP from SavvyCAN_CIBuild.zip to SavvyCAN-Windows_x64_CIBuild.zip to make it more clearer that it is a Windows Build
> Changed Windows Build Name

- mainwindow.cpp
- mainwindow.h
Disable row expansion on new file load and turn off row expansion when row count gets too high
> Fix issue #554

- re/graphingwindow.cpp
This fixes up the graphing windows on high-res displays (tested on macOS) when OpenGL rendering is turned on.
This more then likely needs to be tested on Windows and Linux.
> Fix up double sized opengl graph rendering on high res screens

- dbc/dbcmaineditor.cpp
It seems like when adding a new message it is not setting the background color right away, only after reloading the program. I've added this new state to support new msg and signal
> fix: update msg node color when adding a new message to dbc

- dbc/dbchandler.cpp
The comments should come before attributes in generated DBC files, according to:
- http://mcu.so/Microcontroller/Automotive/DBC_File_Format_Documentation.pdf
- Examples from http://socialledge.com/sjsu/index.php/DBC_Format
This incorrect ordering was tripping up the string parsing grammar of https://github.com/howerj/dbcc which resulted in content after the comments not being parsed at all for me.
**End of generated DBC before:**
**End of generated DBC after:**
> Comments should come before attributes in DBC files

- bus_protocols/isotp_handler.cpp
When being connected to multiple CAN busses the isotp handler picks up first frame messages on all busses and sends flow control messages on the currently scanned bus. 
If there is a lot of UDS communication going on on another bus this causes a lot of unnecessary flow control messages being sent which act like a DoS attack to the scanned unit making it ignore the actual messages at some point so the is scan unreliable.
> issue flow control messages on the scanned bus

- dbc/dbcsignaleditor.cpp
Small usability tweak, allow Ctrl-Z Undo after clicking on the bitfields in the DBC signal editor.
Thanks for all your work on this project @collin80, it's very handy. :)
> dbc signal editor: Allow undo of clicks on bitfield

- mainwindow.cpp
I think this is the right fix here, but of course please let me know if SavvyCAN should do something different:
Right-clicking and trying to graph a signal from a DBC file with "Label filters" unset would result in an error "Cannot find ID 0xNNN in DBC files(). Not adding graph".
Filter labels unset is the default state when adding a new DBC file. Signals from DBC files with "filter labels" unset are still shown in the main CAN messages view when "Interpet Frames" is enabled.
> main window: Fix error on "add to a graphing window" if !filter labels

- connections/serialbusconnection.cpp
- connections/serialbusconnection.h
Add support ListenOnly feature for a Qt SerialBus plugins.
QCanBusDevice::UserKey bit 0 now is responsible for a "Listen Only" or "CAN bus silent" mode
> Add support ListenOnly feature for Qt SerialBus plugins

- framefileio.cpp
Hi,
it seems like CanHacker saves the time locale dependent. Because my .TRC files uses comma instead of dots:
Time     ID        DLC       Data                    Comment
11,201   0F1      4           34 01 00 40             
11,202   1E5      8           4E 00 2D AF FD FF D2 00 
This causes missing timestamps when I load them in SavvyCAN. This PR looks for a comma if no dot is found.
Cheers!
> Add comma check to TRC CanHacker loader

- connections/newconnectiondialog.cpp
I have a FT232-based slcan device which requires to setup serial interface for 3Mbps to operate.
> Add 3000000 baudrate mode for Lawicel device

- mainwindow.cpp
Ensure that the temporary row that is added to the view on startup is sized correctly before storing that height as the default.
Then use the calculated row height to set the default height for all added rows
> Calculate the default row height correctly

- .gitignore
- .vscode/settings.json
- scriptingwindow.cpp
- scriptingwindow.h
- ui/scriptingwindow.ui
Enhancements to the scripting interface to improve usability
1. Added a "Save As" button which does what "Save" used to do (prompt for a filename and save to it) and changed "Save" to write to the filename we already know for the current script. This makes saving as you work easier, and still allows making a copy if you don't want to overwrite the original
2. Added a "Reload" button that reloads the script from disk (prompting for verification) and then recompiles it. This makes it easy to use an external editor and just reload in SavvyCAN (otherwise you have to delete/load)
3. Added a "Save Log" button to save the current log window contents to a file
All buttons are in the tab order/index and have quick keys.
> Scripting Interface Enhancements

- dbc/dbc_classes.cpp
These extra newlines could consume a lot of screen estate if multiple rows are "highlighted":
so I added some logic to remove them.
> Do not add extra trailing newline on the decoded message texts

- SavvyCAN.pro
- connections/lawicel_serial.cpp
I have updated project properties, because there are a few `[[fallthrough]]` attributes in the code, that requires support of C++17.
Also I fixed gcc complains about it in the Lawicel protocol.
I hope in 2024 all alive compilers able to support it ;-)
> Update required C++ standard to C++17

- firmwareuploaderwindow.cpp
I know that this module now is not used, but it still makes a few compiler warnings.
So, I found here 2 issues:
- allocating `CANFrame` on a heap lead memory leaks
- Qt made a bad design of `QCanBusFrame`, where `payload()` returns a copy of data instead of reference to it. So, I don't understand how you tested it, but populating of frame data is not working at all and even can cause memory overflow.
> Fix FirmwareUpdater

- connections/connectionwindow.cpp
In some cases connection between `CANConnection::debugOutput` and `ConnectionWindow::getDebugText` can be requested several times, that lead to string duplication in the window (for example, #713).
Easiest way to fix it - declare connection as unique.
> ConnectionWindow: fix Device Console duplicates

- dbc/dbchandler.cpp
- dbc/dbchandler.h
SIG_VALTYPE_ is accepted by other can parsers (e.g. python cantools). this patch adds support for DBCs using it.
> add support for SIG_VALTYPE_ to specify floating point signals

- SavvyCAN.pro
This provides a more helpful compile-time error
message, hopefully preventing issues like #727
(https://github.com/collin80/SavvyCAN/issues/727).
> make qmake check Qt version

- dbc/dbc_classes.cpp
Instead of rendering as "45Celsius" it now renders as "45 Celsius".
Before:
After:
> signal makePrettyOutput: add a space between value and unit

- README.md
- framefileio.cpp
- framefileio.h
- pcaplite.cpp
- pcaplite.h
This PR Adds support for reading Wireshark SocketCAN logs. There is currently a Wireshark pcap decoder in SavvyCAN but not for these types of logs. The new code checks if the pcap file link type is PCAP_LINKTYPE_SOCKETCAN (227) and if not, will fall through to the current default wireshark decoder.
This work is in addition to the PR I will soon create that adds gs_usb (cantact, canable, CAN Bus Debugger etc.) support on Windows as discussed in Issue #238
Let me know if there is anything you'd like me to modify.
Thanks for great work!
> Add support for reading Wireshark SocketCAN log format

- dbc/dbchandler.cpp
Every version I've tried fails to match the ID to the comment in the dbc. Upon saving, comments are lost from the database. These changes prevent that from happening.
> Fix dbc handling of comments and attributes

- connections/connectionwindow.cpp
By following these steps:
1. Connect to device through Connection -> Add New Device Connection
2. Wait until device is connected
3. Change baudrate
4. Save Bus Settings
The changes would not persist, and you would need to change baudrate again.
This was happening because after running `connModel->refresh();`, the selection of `ui->tableConnections` would be lost.
> Fix device deselection after connecting

- .github/workflows/build.yml
- framefileio.cpp
I have a candump log with the following data:
(1727438342.368435)  can0       0C0  [32]  03 F5 FE E7 FF 10 27 00 E0 FF FF F3 3F FF F3 3F FC EF FF FD FF FF FE 07 00 00 00 00 00 00 00 00
(1727438342.372671)  can0       583  [08]  00 00 80 00 10 40 40 40
The current candump parser only looks at the first number after the [ character.
> Add support for > 8 bytes per message in candump format

- connections/newconnectiondialog.cpp
- connections/socketcand.cpp
When socketcand reconnecting, it will always failed because not reset socketcand mode.
At the same time, a strange problem that required adding ")" at the end of bus to work was removed.
> Fix socketcand connection unexpectedly reconnecting;

- connections/canconfactory.cpp
- connections/canconnection.cpp
- connections/canconnection.h
- connections/connectionwindow.cpp
- connections/serialbusconnection.cpp
- connections/serialbusconnection.h
- framefileio.cpp
I found a bug that analyzed and saved CAN frames that are extended frames in real but with ids in the standard id range as shorted standard frames only.
This has been corrected here for all available PCAN file reads.
> Corrected extended CAN ID read for IDs < 0x800

- dbc/dbchandler.cpp
During last refactoring you made a typo that breaks GMLAN parser.
`master` branch should work fine (haven't tested it, I'm using the only Qt6 version)
> Fix GMLAN DBC reading

- dbc/dbchandler.cpp
Fixed addmultiplexrange in DBC_SIGNAL
I found it after getting the following build error:
> dbc/dbchandler.cpp:467:10: error: ‘class DBC_SIGNAL’ has no member named ‘multiplexLowValue’
> Fixed addmultiplexrange

- dbc/dbcloadsavewindow.cpp
Wrong name for 'filterlabeling' attribute leads to junk in some cases:
```
BA_DEF_ BO_ "GenMsgBackgroundColor" STRING ;
BA_DEF_ BO_ "GenMsgForegroundColor" STRING ;
BA_DEF_ BO_ "labelfilters" INT 0 0;
BA_DEF_ BO_ "labelfilters" INT 0 0;
BA_DEF_ BO_ "labelfilters" INT 0 0;
BA_DEF_DEF_ "GenMsgBackgroundColor" "#ffffff";
BA_DEF_DEF_ "GenMsgForegroundColor" "#000000";
BA_DEF_DEF_ "labelfilters" 1;
BA_DEF_DEF_ "labelfilters" 0;
BA_DEF_DEF_ "labelfilters" 1;
```
can be reproduced on master branch as well.
> DBC filter labeling attribute wrong name

- dbc/dbchandler.cpp
Fixed the boolean values saving by adding this type check on save, as discussed on #954
> fix: Add support for boolean attribute values in DBC file saving
